site_name: BioJulia MkDocs Theme
theme_dir: mkdocs-biojulia
site_author: The BioJulia Organisation
site_description: "MkDocs theme used by the BioJulia organisation for manual pages."
repo_url: "https://github.com/chrissimpkins/cinder"
copyright: "MkDocs BioJulia is licensed under the <a href='https://github.com/BioJulia/mkdocs-biojulia/blob/master/LICENSE.md'>MIT license</a>"
pages:
  - Home: index.md
  - Specimen: specimen.md
